### ISSUE TITLE
F26 rebuild TODO

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#76]
* [x] xmltv
* [x] mythtv, mythtv-web, mythtv-status
* [x] opera
* [x] chromium
* [x] libtxc_dxtn(+i386)
* [x] libva-intel-driver (+i386)
* [x] openshot
* [x] steam
* [x] smplayer
* [x] moc
* [x] tribler
* [x] syncthing
* [x] sox-plugins-freeworld
* [x] spotify-client, openssl1
* [x] n1
* [x] uld
* [x] libdvdcss
* [x] exfat-utils
* [x] brackets

**Comment by paulcarroty** [comment]
@kuboosoft because chromium from F26 crash every 5-10 min I've added F25.
